// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.event.list",
			Path:         []string{"session", "event", "list"},
			Use:          "list",
			Short:        "List events in a session",
			Examples:     []string{"Example - List recent session events:\n  agr session event list --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --limit 50"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeEventsResponse",
				Description: "DescribeEventsResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
			{Path: []string{"session", "event"}, Use: "event", Short: "Manage session events"},
		},
		API: apicli.APISpec{
			Action:       "DescribeEvents",
			RequestType:  "DescribeEventsRequest",
			ResponseType: "DescribeEventsResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Author",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "author", Flag: "author", Usage: "事件作者。取值示例：user、assistant、tool。", Type: command.FlagString},
				},
			},
			{
				Name:   "AfterTimestamp",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "after-timestamp", Flag: "after-timestamp", Usage: "起始时间，仅返回该时间之后的事件，使用 RFC3339 格式，最大长度 64 字符。", Type: command.FlagString},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "分页偏移量，默认为 0。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "返回数量，默认为 50，最大值为 200。", Type: command.FlagInt},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
