// Code generated by cobragen; DO NOT EDIT.

package downloadurl

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.skill-package.download-url",
			Path:         []string{"registry", "skill-package", "download-url"},
			Use:          "download-url",
			Short:        "Get a skill package download URL",
			Long:         "Get a short-lived download URL for a ready TAR_PACKAGE skill version. Select VersionId or Label, not both. This command returns the URL; it does not download a file.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "GetSkillPackageDownloadURLResponse",
				Description: "GetSkillPackageDownloadURLResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "skill-package"}, Use: "skill-package", Short: "Manage skill-package"},
		},
		API: apicli.APISpec{
			Action:       "GetSkillPackageDownloadURL",
			RequestType:  "GetSkillPackageDownloadURLRequest",
			ResponseType: "GetSkillPackageDownloadURLResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "Label",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "label", Flag: "label", Usage: "Version label; mutually exclusive with version-id.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
