// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session-space.list",
			Path:         []string{"session-space", "list"},
			Use:          "list",
			Short:        "List session spaces",
			Examples:     []string{"Example - List session spaces:\n  agr session-space list --limit 20"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSessionSpacesResponse",
				Description: "DescribeSessionSpacesResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session-space"}, Use: "session-space", Short: "Manage session spaces"},
		},
		API: apicli.APISpec{
			Action:       "DescribeSessionSpaces",
			RequestType:  "DescribeSessionSpacesRequest",
			ResponseType: "DescribeSessionSpacesResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "分页查询的起始偏移量。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "单次分页查询返回的会话空间数量。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Filters as a JSON array, @file, or - for stdin.", Format: "[{\"Name\":\"name-like\",\"Values\":[\"example\"]}]", Fields: []string{"At most 3 distinct filters; name and name-like are mutually exclusive", "1–100 nonblank values per filter, at most 128 Unicode characters each", "Values are OR, filters are AND; case-sensitive literal matching before pagination"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
