// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.get",
			Path:         []string{"session", "get"},
			Use:          "get",
			Short:        "Describe a session",
			Long:         "Describe a session. Optionally request recent events with --num-recent-events and an RFC3339 --after-timestamp filter.",
			Examples:     []string{"Example - Describe a session:\n  agr session get --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123", "Example - Include recent events:\n  agr session get --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --num-recent-events 10 --after-timestamp 2026-09-01T00:00:00Z"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSessionResponse",
				Description: "DescribeSessionResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "DescribeSession",
			RequestType:  "DescribeSessionRequest",
			ResponseType: "DescribeSessionResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "NumRecentEvents",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "num-recent-events", Flag: "num-recent-events", Usage: "Number of recent events to include.", Type: command.FlagInt},
				},
			},
			{
				Name:   "AfterTimestamp",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "after-timestamp", Flag: "after-timestamp", Usage: "Only include events after this RFC3339 timestamp.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
