// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.get",
			Path:         []string{"registry", "get"},
			Use:          "get",
			Short:        "Get a registry",
			Long:         "Get a registry.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeRegistryResponse",
				Description: "DescribeRegistryResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
		},
		API: apicli.APISpec{
			Action:       "DescribeRegistry",
			RequestType:  "DescribeRegistryRequest",
			ResponseType: "DescribeRegistryResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
