//go:build !preview

// Code generated by cobragen; DO NOT EDIT.

package commands

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
	apicall "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/api/call"
	apikeycreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/create"
	apikeydelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/delete"
	apikeylist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/list"
	credentialoauth2acquire "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/oauth2/acquire"
	credentialoauth2complete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/oauth2/complete"
	credentialprovidercreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/provider/create"
	credentialproviderdelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/provider/delete"
	credentialproviderget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/provider/get"
	credentialproviderlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/provider/list"
	credentialproviderupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/provider/update"
	credentialsecretdelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/secret/delete"
	credentialsecretget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/secret/get"
	credentialsecretlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/secret/list"
	credentialsecretset "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/credential/secret/set"
	deploymentcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/create"
	deploymentdelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/delete"
	deploymentget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/get"
	deploymentlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/list"
	deploymentproxy "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/proxy"
	deploymentupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/deployment/update"
	identitycreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/create"
	identitydelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/delete"
	identityget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/get"
	identitylist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/list"
	identitytokencreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/token/create"
	identityupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/identity/update"
	instancebrowservnc "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/browser/vnc"
	instancecoderun "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/code/run"
	instancecreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/create"
	instancedebug "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/debug"
	instancedelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/delete"
	instanceexec "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/exec"
	instancefiledownload "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/file/download"
	instancefileupload "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/file/upload"
	instanceget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/get"
	instancelist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/list"
	instancelogin "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/login"
	instancemobileadb "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/adb"
	instancemobileconnect "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/connect"
	instancemobiledisconnect "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/disconnect"
	instancemobilelist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/list"
	instancemobiletunnel "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/tunnel"
	instancepause "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/pause"
	instanceproxy "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/proxy"
	instanceresume "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/resume"
	instanceupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/update"
	precacheimagetaskcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/precacheimagetask/create"
	precacheimagetaskget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/precacheimagetask/get"
	registryauditloglist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/auditlog/list"
	registrycreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/create"
	registrydelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/delete"
	registryget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/get"
	registrylist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/list"
	registryrecordapprove "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/approve"
	registryrecordcancel "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/cancel"
	registryrecordcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/create"
	registryrecorddelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/delete"
	registryrecordget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/get"
	registryrecordlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/list"
	registryrecordpreview "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/preview"
	registryrecordreject "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/reject"
	registryrecordsync "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/sync"
	registryrecordupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/update"
	registryrecordversionlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/record/version/list"
	registryskillpackagedownloadurl "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/skillpackage/downloadurl"
	registryskillpackageuploadurl "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/skillpackage/uploadurl"
	registryupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/registry/update"
	sessioncreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/create"
	sessiondelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/delete"
	sessioneventappend "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/event/append"
	sessioneventlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/event/list"
	sessionget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/get"
	sessionlist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/list"
	sessionupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/session/update"
	sessionspacecreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/sessionspace/create"
	sessionspacedelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/sessionspace/delete"
	sessionspaceget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/sessionspace/get"
	sessionspacelist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/sessionspace/list"
	sessionspaceupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/sessionspace/update"
	toolcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/create"
	tooldelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/delete"
	toolfork "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/fork"
	toolget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/get"
	toollist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/list"
	toolupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/update"
)

func Registry() (*command.Registry, error) {
	registry := command.NewRegistry()
	for _, module := range []command.Module{
		apicall.Module(),
		apikeycreate.Module(),
		apikeydelete.Module(),
		apikeylist.Module(),
		credentialoauth2acquire.Module(),
		credentialoauth2complete.Module(),
		credentialprovidercreate.Module(),
		credentialproviderdelete.Module(),
		credentialproviderget.Module(),
		credentialproviderlist.Module(),
		credentialproviderupdate.Module(),
		credentialsecretdelete.Module(),
		credentialsecretget.Module(),
		credentialsecretlist.Module(),
		credentialsecretset.Module(),
		deploymentcreate.Module(),
		deploymentdelete.Module(),
		deploymentget.Module(),
		deploymentlist.Module(),
		deploymentproxy.Module(),
		deploymentupdate.Module(),
		identitycreate.Module(),
		identitydelete.Module(),
		identityget.Module(),
		identitylist.Module(),
		identitytokencreate.Module(),
		identityupdate.Module(),
		instancebrowservnc.Module(),
		instancecoderun.Module(),
		instancecreate.Module(),
		instancedebug.Module(),
		instancedelete.Module(),
		instanceexec.Module(),
		instancefiledownload.Module(),
		instancefileupload.Module(),
		instanceget.Module(),
		instancelist.Module(),
		instancelogin.Module(),
		instancemobileadb.Module(),
		instancemobileconnect.Module(),
		instancemobiledisconnect.Module(),
		instancemobilelist.Module(),
		instancemobiletunnel.Module(),
		instancepause.Module(),
		instanceproxy.Module(),
		instanceresume.Module(),
		instanceupdate.Module(),
		precacheimagetaskcreate.Module(),
		precacheimagetaskget.Module(),
		registryauditloglist.GeneratedModule(),
		registrycreate.GeneratedModule(),
		registrydelete.GeneratedModule(),
		registryget.GeneratedModule(),
		registrylist.GeneratedModule(),
		registryrecordapprove.GeneratedModule(),
		registryrecordcancel.GeneratedModule(),
		registryrecordcreate.GeneratedModule(),
		registryrecorddelete.GeneratedModule(),
		registryrecordget.GeneratedModule(),
		registryrecordlist.GeneratedModule(),
		registryrecordpreview.GeneratedModule(),
		registryrecordreject.GeneratedModule(),
		registryrecordsync.GeneratedModule(),
		registryrecordupdate.GeneratedModule(),
		registryrecordversionlist.GeneratedModule(),
		registryskillpackagedownloadurl.GeneratedModule(),
		registryskillpackageuploadurl.GeneratedModule(),
		registryupdate.GeneratedModule(),
		sessionspacecreate.GeneratedModule(),
		sessionspacedelete.GeneratedModule(),
		sessionspaceget.GeneratedModule(),
		sessionspacelist.GeneratedModule(),
		sessionspaceupdate.GeneratedModule(),
		sessioncreate.GeneratedModule(),
		sessiondelete.GeneratedModule(),
		sessioneventappend.GeneratedModule(),
		sessioneventlist.GeneratedModule(),
		sessionget.GeneratedModule(),
		sessionlist.GeneratedModule(),
		sessionupdate.GeneratedModule(),
		toolcreate.Module(),
		tooldelete.Module(),
		toolfork.Module(),
		toolget.Module(),
		toollist.Module(),
		toolupdate.Module(),
	} {
		if err := registry.Register(module); err != nil {
			return nil, err
		}
	}
	return registry, nil
}
