// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.audit-log.list",
			Path:         []string{"registry", "audit-log", "list"},
			Use:          "list",
			Short:        "List registry audit logs",
			Long:         "List registry audit logs.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeRegistryAuditLogListResponse",
				Description: "DescribeRegistryAuditLogListResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "audit-log"}, Use: "audit-log", Short: "Manage audit-log"},
		},
		API: apicli.APISpec{
			Action:       "DescribeRegistryAuditLogList",
			RequestType:  "DescribeRegistryAuditLogListRequest",
			ResponseType: "DescribeRegistryAuditLogListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "RecordId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "ActionFilter",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "action-filter", Flag: "action-filter", Usage: "Audit action filter.", Type: command.FlagString},
				},
			},
			{
				Name:   "Actor",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "actor", Flag: "actor", Usage: "Audit actor filter.", Type: command.FlagString},
				},
			},
			{
				Name:   "StartTime",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "start-time", Flag: "start-time", Usage: "Audit range start time.", Type: command.FlagString},
				},
			},
			{
				Name:   "EndTime",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "end-time", Flag: "end-time", Usage: "Audit range end time.", Type: command.FlagString},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset.", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Maximum number of results.", Type: command.FlagInt},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
