// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session-space.create",
			Path:         []string{"session-space", "create"},
			Use:          "create",
			Short:        "Create a session space",
			Examples:     []string{"Example - Create a session space:\n  agr session-space create --name customer-support --description 'Customer support sessions'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateSessionSpaceResponse",
				Description: "CreateSessionSpaceResponse response.",
				Effects:     []string{"create:session-space"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session-space"}, Use: "session-space", Short: "Manage session spaces"},
		},
		API: apicli.APISpec{
			Action:       "CreateSessionSpace",
			RequestType:  "CreateSessionSpaceRequest",
			ResponseType: "CreateSessionSpaceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "Name",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "name", Flag: "name", Usage: "会话空间名称，用于标识会话空间的业务用途。入参限制：必填；去除首尾空白后不能为空；最大长度为 128 个字符。建议名称包含业务和环境信息，便于识别和管理。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "会话空间描述，用于补充说明会话空间的业务用途。入参限制：选填；最大长度为 512 个字符。未传入时创建为空描述。", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Resource tags as a JSON array, @file, or - for stdin.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
