// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.update",
			Path:         []string{"registry", "record", "update"},
			Use:          "update",
			Short:        "Update record metadata, labels, or content",
			Long:         "Update Description and/or LabelMutations, or provide exactly one content source to create a new version. Content cannot be combined with Description or LabelMutations. VersionName and ChangeLog describe the new version. LabelMutations uses Operation, Name, optional VersionId and Reason; stable/latest labels cannot be deleted. Approval does not assign the stable label.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "UpdateRegistryRecordResponse",
				Description: "UpdateRegistryRecordResponse response.",
				Effects:     []string{"update:registry-record", "create:registry-record-version"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "UpdateRegistryRecord",
			RequestType:  "UpdateRegistryRecordRequest",
			ResponseType: "UpdateRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:       "Description",
				AllowEmpty: true,
				Parser:     "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "Description; pass an empty string to clear it.", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-name", Flag: "version-name", Usage: "Name for the new version.", Type: command.FlagString},
				},
			},
			{
				Name:   "ChangeLog",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "change-log", Flag: "change-log", Usage: "Change log for the new version.", Type: command.FlagString},
				},
			},
			{
				Name:   "MCPSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "mcp-source", Flag: "mcp-source", Usage: "MCP source: Type, Descriptors (JSON string), or EndpointURL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "AgentSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "agent-source", Flag: "agent-source", Usage: "Agent source: Type, Descriptors (JSON string), or EndpointURL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "SkillSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "skill-source", Flag: "skill-source", Usage: "Skill source: Type (MANUAL/TAR_PACKAGE) and SkillMd for MANUAL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "CustomDescriptors",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "custom-descriptors", Flag: "custom-descriptors", Usage: "CUSTOM descriptors as a JSON object encoded in a string; use --request @file for file input.", Type: command.FlagString},
				},
			},
			{
				Name:   "LabelMutations",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "label-mutations", Flag: "label-mutations", Usage: "Label operations: Operation, Name, VersionId and Reason. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
