// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.create",
			Path:         []string{"registry", "create"},
			Use:          "create",
			Short:        "Create a registry",
			Long:         "Create a registry.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateRegistryResponse",
				Description: "CreateRegistryResponse response.",
				Effects:     []string{"create:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
		},
		API: apicli.APISpec{
			Action:       "CreateRegistry",
			RequestType:  "CreateRegistryRequest",
			ResponseType: "CreateRegistryResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "Name",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "name", Flag: "name", Usage: "Resource name. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "Description; pass an empty string to clear it.", Type: command.FlagString},
				},
			},
			{
				Name:   "ApprovalMode",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "approval-mode", Flag: "approval-mode", Usage: "Approval mode: AUTO or MANUAL; immutable after creation.", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Cloud tags as Key/Value objects. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
