// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session-space.update",
			Path:         []string{"session-space", "update"},
			Use:          "update",
			Short:        "Update a session space",
			Examples:     []string{"Example - Rename a session space:\n  agr session-space update --space-id space-a1b2c3d4 --name customer-support-production"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "ModifySessionSpaceResponse",
				Description: "ModifySessionSpaceResponse response.",
				Effects:     []string{"update:session-space"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session-space"}, Use: "session-space", Short: "Manage session spaces"},
		},
		API: apicli.APISpec{
			Action:       "ModifySessionSpace",
			RequestType:  "ModifySessionSpaceRequest",
			ResponseType: "ModifySessionSpaceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "需要修改的会话空间唯一标识。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Name",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "name", Flag: "name", Usage: "修改后的会话空间名称。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "修改后的会话空间描述。", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
