// Code generated by cobragen; DO NOT EDIT.

package approve

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.approve",
			Path:         []string{"registry", "record", "approve"},
			Use:          "approve",
			Short:        "Approve a record version",
			Long:         "Approve a record version.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "ApproveRegistryRecordResponse",
				Description: "ApproveRegistryRecordResponse response.",
				Effects:     []string{"update:registry-record-version"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "ApproveRegistryRecord",
			RequestType:  "ApproveRegistryRecordRequest",
			ResponseType: "ApproveRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "VersionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Comment",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "comment", Flag: "comment", Usage: "Approval decision comment. (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
