// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.delete",
			Path:         []string{"registry", "record", "delete"},
			Use:          "delete",
			Short:        "Delete a record or a version",
			Long:         "Without VersionId, delete the entire record. With VersionId, delete only that version. The service enforces label references and version state restrictions. This command does not bypass those checks. An explicitly empty --version-id is sent as an empty selector and rejected by the service; it never means deleting the entire record.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteRegistryRecordResponse",
				Description: "DeleteRegistryRecordResponse response.",
				Effects:     []string{"delete:registry-record"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "DeleteRegistryRecord",
			RequestType:  "DeleteRegistryRecordRequest",
			ResponseType: "DeleteRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:       "VersionId",
				AllowEmpty: true,
				Parser:     "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "Reason",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "reason", Flag: "reason", Usage: "Reason for deletion.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
