// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.delete",
			Path:         []string{"session", "delete"},
			Use:          "delete",
			Short:        "Delete a session",
			Examples:     []string{"Example - Delete a session:\n  agr session delete --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123"},
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteSessionResponse",
				Description: "DeleteSessionResponse response.",
				Effects:     []string{"delete:session"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "DeleteSession",
			RequestType:  "DeleteSessionRequest",
			ResponseType: "DeleteSessionResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
