// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session-space.get",
			Path:         []string{"session-space", "get"},
			Use:          "get",
			Short:        "Describe a session space",
			Examples:     []string{"Example - Describe a session space:\n  agr session-space get --space-id space-a1b2c3d4"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSessionSpaceResponse",
				Description: "DescribeSessionSpaceResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session-space"}, Use: "session-space", Short: "Manage session spaces"},
		},
		API: apicli.APISpec{
			Action:       "DescribeSessionSpace",
			RequestType:  "DescribeSessionSpaceRequest",
			ResponseType: "DescribeSessionSpaceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "需要查询的会话空间唯一标识。入参限制：必填，不能为空。可通过 CreateSessionSpace 或 DescribeSessionSpaces 获取，不应自行构造。 (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
