// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.create",
			Path:         []string{"session", "create"},
			Use:          "create",
			Short:        "Create a session",
			Long:         "Create a session in a session space. Complex state and metadata fields accept inline JSON, @file, or - for stdin.",
			Examples:     []string{"Example - Create a session with a stable ID:\n  agr session create --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --title 'Support request'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateSessionResponse",
				Description: "CreateSessionResponse response.",
				Effects:     []string{"create:session"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "CreateSession",
			RequestType:  "CreateSessionRequest",
			ResponseType: "CreateSessionResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "SessionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。", Type: command.FlagString},
				},
			},
			{
				Name:   "Title",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "title", Flag: "title", Usage: "会话标题，最大长度 256 字符。", Type: command.FlagString},
				},
			},
			{
				Name:   "State",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "state", Flag: "state", Usage: "Initial session state as a JSON object, @file, or - for stdin.", Format: "{\"CustomState\":\"<json-string>\"}", Fields: []string{"CustomState: serialized custom state JSON"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Metadata",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "metadata", Flag: "metadata", Usage: "Initial session metadata as a JSON array, @file, or - for stdin.", Format: "[{\"Name\":\"<name>\",\"Value\":\"<value>\"}]", Fields: []string{"Name: metadata name", "Value: metadata value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
