// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.list",
			Path:         []string{"session", "list"},
			Use:          "list",
			Short:        "List sessions",
			Examples:     []string{"Example - List sessions in a session space:\n  agr session list --space-id space-a1b2c3d4 --limit 20"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSessionsResponse",
				Description: "DescribeSessionsResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "DescribeSessions",
			RequestType:  "DescribeSessionsRequest",
			ResponseType: "DescribeSessionsResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "查询的会话空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "UserIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "user-ids", Flag: "user-ids", Usage: "User ID filter; repeat --user-ids for multiple values.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "分页偏移量，默认为 0。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "返回数量，默认为 20，最大值为 100。", Type: command.FlagInt},
				},
			},
			{
				Name:   "SessionIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "session-ids", Flag: "session-ids", Usage: "Session ID filter; repeat --session-ids for multiple values.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Session metadata filters as a JSON array, @file, or - for stdin.", Format: "[{\"Name\":\"metadata:<key>\",\"Values\":[\"<value>\"]}]", Fields: []string{"Name: metadata:<key>", "Values: accepted values for the metadata key"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
