// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.get",
			Path:         []string{"registry", "record", "get"},
			Use:          "get",
			Short:        "Get a record and resolve a version",
			Long:         "Select a version using either --version-id or --label, not both. Omit both to use the service default selector. The response includes Record, Version, ResolvedBy and ResolvedLabel.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeRegistryRecordResponse",
				Description: "DescribeRegistryRecordResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "DescribeRegistryRecord",
			RequestType:  "DescribeRegistryRecordRequest",
			ResponseType: "DescribeRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "Label",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "label", Flag: "label", Usage: "Version label; mutually exclusive with version-id.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
