// Code generated by cobragen; DO NOT EDIT.

package uploadurl

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.skill-package.upload-url",
			Path:         []string{"registry", "skill-package", "upload-url"},
			Use:          "upload-url",
			Short:        "Get a skill package upload URL",
			Long:         "Get a short-lived upload URL for an existing TAR_PACKAGE skill version. This command returns the URL; it does not upload a file. Upload the archive with HTTP PUT and check content readiness through registry record get.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "GetSkillPackageUploadURLResponse",
				Description: "GetSkillPackageUploadURLResponse response.",
				Effects:     []string{"update:registry-skill-package"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "skill-package"}, Use: "skill-package", Short: "Manage skill-package"},
		},
		API: apicli.APISpec{
			Action:       "GetSkillPackageUploadURL",
			RequestType:  "GetSkillPackageUploadURLRequest",
			ResponseType: "GetSkillPackageUploadURLResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "VersionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID. (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
