// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session-space.delete",
			Path:         []string{"session-space", "delete"},
			Use:          "delete",
			Short:        "Delete a session space",
			Examples:     []string{"Example - Delete an empty session space:\n  agr session-space delete --space-id space-a1b2c3d4"},
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteSessionSpaceResponse",
				Description: "DeleteSessionSpaceResponse response.",
				Effects:     []string{"delete:session-space"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session-space"}, Use: "session-space", Short: "Manage session spaces"},
		},
		API: apicli.APISpec{
			Action:       "DeleteSessionSpace",
			RequestType:  "DeleteSessionSpaceRequest",
			ResponseType: "DeleteSessionSpaceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "需要删除的会话空间唯一标识。 (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
