// Code generated by cobragen; DO NOT EDIT.

package preview

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.preview",
			Path:         []string{"registry", "record", "preview"},
			Use:          "preview",
			Short:        "Preview remote record changes",
			Long:         "Only remote MCP/A2A sources support preview. VersionId and Label are mutually exclusive. PreviewResult is JSON text returned by the service.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "PreviewRegistryRecordResponse",
				Description: "PreviewRegistryRecordResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "PreviewRegistryRecord",
			RequestType:  "PreviewRegistryRecordRequest",
			ResponseType: "PreviewRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "Label",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "label", Flag: "label", Usage: "Version label; mutually exclusive with version-id.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
