// Code generated by cobragen; DO NOT EDIT.

package sync

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.sync",
			Path:         []string{"registry", "record", "sync"},
			Use:          "sync",
			Short:        "Synchronize a remote record source",
			Long:         "Only remote MCP/A2A sources support synchronization. VersionId and Label are mutually exclusive. A successful API call may report a synchronization error in SyncStatus/ErrorCode/ErrorMessage; inspect the response.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "SyncRegistryRecordResponse",
				Description: "SyncRegistryRecordResponse response.",
				Effects:     []string{"update:registry-record", "create:registry-record-version"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "SyncRegistryRecord",
			RequestType:  "SyncRegistryRecordRequest",
			ResponseType: "SyncRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "RecordId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "record-id", Flag: "record-id", Usage: "Record ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-id", Flag: "version-id", Usage: "Record version ID.", Type: command.FlagString},
				},
			},
			{
				Name:   "Label",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "label", Flag: "label", Usage: "Version label; mutually exclusive with version-id.", Type: command.FlagString},
				},
			},
			{
				Name:   "ChangeLog",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "change-log", Flag: "change-log", Usage: "Change log for the new version.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
