// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.update",
			Path:         []string{"session", "update"},
			Use:          "update",
			Short:        "Update a session",
			Long:         "Update a session title or replace its complete metadata array. Provide at least one of --title or --metadata.",
			Examples:     []string{"Example - Update a session title:\n  agr session update --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --title 'Resolved request'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "ModifySessionResponse",
				Description: "ModifySessionResponse response.",
				Effects:     []string{"update:session"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "ModifySession",
			RequestType:  "ModifySessionRequest",
			ResponseType: "ModifySessionResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属的 SessionSpace ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "会话所属的用户 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "待修改的会话 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Title",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "title", Flag: "title", Usage: "修改后的会话标题。入参限制：本参数可选，最大长度为 255 个字符。不传表示保持原会话标题不变，传空字符串表示清空会话标题。Title 与 Metadata 至少传入一项。", Type: command.FlagString},
				},
			},
			{
				Name:   "Metadata",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "metadata", Flag: "metadata", Usage: "Complete session metadata as a JSON array, @file, or - for stdin. [] clears all metadata.", Format: "[{\"Name\":\"<name>\",\"Value\":\"<value>\"}]", Fields: []string{"Name: metadata name", "Value: metadata value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
