// Code generated by cobragen; DO NOT EDIT.

package append

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.event.append",
			Path:         []string{"session", "event", "append"},
			Use:          "append",
			Short:        "Append an event to a session",
			Long:         "Append an event to a session. The event accepts inline JSON, @file, or - for stdin.",
			Examples:     []string{"Example - Append a user event:\n  agr session event append --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --event '{\"EventId\":\"event-123\",\"Author\":\"user\",\"Content\":{\"Role\":\"user\",\"Parts\":[{\"Text\":\"Hello\"}]}}'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "AppendEventResponse",
				Description: "AppendEventResponse response.",
				Effects:     []string{"create:event"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
			{Path: []string{"session", "event"}, Use: "event", Short: "Manage session events"},
		},
		API: apicli.APISpec{
			Action:       "AppendEvent",
			RequestType:  "AppendEventRequest",
			ResponseType: "AppendEventResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Event",
				Required: true,
				Parser:   "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "event", Flag: "event", Usage: "Event content as a JSON object, @file, or - for stdin. (required)", Format: "{\"EventId\":\"<id>\",\"Author\":\"<author>\",\"Content\":{\"Role\":\"<role>\",\"Parts\":[{\"Text\":\"<text>\"}]}}", Fields: []string{"EventId: optional stable event ID for idempotent retries", "Author: event author", "Content: structured event content", "Actions: optional state delta", "Metadata: optional event metadata JSON string", "Extensions: optional extension JSON string"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
