// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.record.create",
			Path:         []string{"registry", "record", "create"},
			Use:          "create",
			Short:        "Create a record and its first version",
			Long:         "Provide exactly one content source matching --descriptor-type: MCP uses --mcp-source; A2A and AGUI use --agent-source; AGENT_SKILLS uses --skill-source; CUSTOM uses --custom-descriptors. Source objects accept inline JSON, @file, or - for stdin. Descriptors inside a source are JSON strings, not nested objects. Approval and assigning the stable label are separate operations.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateRegistryRecordResponse",
				Description: "CreateRegistryRecordResponse response.",
				Effects:     []string{"create:registry-record", "create:registry-record-version"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
			{Path: []string{"registry", "record"}, Use: "record", Short: "Manage record"},
		},
		API: apicli.APISpec{
			Action:       "CreateRegistryRecord",
			RequestType:  "CreateRegistryRecordRequest",
			ResponseType: "CreateRegistryRecordResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Name",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "name", Flag: "name", Usage: "Resource name. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "DescriptorType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "descriptor-type", Flag: "descriptor-type", Usage: "Content type: MCP, A2A, AGUI, AGENT_SKILLS, or CUSTOM. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "Description; pass an empty string to clear it.", Type: command.FlagString},
				},
			},
			{
				Name:   "VersionName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "version-name", Flag: "version-name", Usage: "Name for the new version.", Type: command.FlagString},
				},
			},
			{
				Name:   "MCPSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "mcp-source", Flag: "mcp-source", Usage: "MCP source: Type, Descriptors (JSON string), or EndpointURL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "AgentSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "agent-source", Flag: "agent-source", Usage: "Agent source: Type, Descriptors (JSON string), or EndpointURL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "SkillSource",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "skill-source", Flag: "skill-source", Usage: "Skill source: Type (MANUAL/TAR_PACKAGE) and SkillMd for MANUAL. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
			{
				Name:   "CustomDescriptors",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "custom-descriptors", Flag: "custom-descriptors", Usage: "CUSTOM descriptors as a JSON object encoded in a string; use --request @file for file input.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
