// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.list",
			Path:         []string{"registry", "list"},
			Use:          "list",
			Short:        "List registries",
			Long:         "List registries.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeRegistryListResponse",
				Description: "DescribeRegistryListResponse response.",
				Effects:     []string{"read:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
		},
		API: apicli.APISpec{
			Action:       "DescribeRegistryList",
			RequestType:  "DescribeRegistryListRequest",
			ResponseType: "DescribeRegistryListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset.", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Maximum number of results.", Type: command.FlagInt},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Filters as Name/Values objects. Accepts JSON, @file, or - for stdin.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
