// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.update",
			Path:         []string{"registry", "update"},
			Use:          "update",
			Short:        "Update a registry description",
			Long:         "Update a registry description.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "UpdateRegistryResponse",
				Description: "UpdateRegistryResponse response.",
				Effects:     []string{"update:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
		},
		API: apicli.APISpec{
			Action:       "UpdateRegistry",
			RequestType:  "UpdateRegistryRequest",
			ResponseType: "UpdateRegistryResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
			{
				Name:       "Description",
				AllowEmpty: true,
				Required:   true,
				Parser:     "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Usage: "Description; pass an empty string to clear it. (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
