// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "registry.delete",
			Path:         []string{"registry", "delete"},
			Use:          "delete",
			Short:        "Delete an empty registry",
			Long:         "Delete an empty registry.",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteRegistryResponse",
				Description: "DeleteRegistryResponse response.",
				Effects:     []string{"delete:registry"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"registry"}, Use: "registry", Short: "Manage registry"},
		},
		API: apicli.APISpec{
			Action:       "DeleteRegistry",
			RequestType:  "DeleteRegistryRequest",
			ResponseType: "DeleteRegistryResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "RegistryId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "registry-id", Flag: "registry-id", Usage: "Registry ID. (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
